### ISSUE TITLE
Add info about new figures

### ISSUE THREAD

**Issue by tanjot** [carts-uiet/bus_boarding_paper#15]
Add description about values in following figures:

- [x] UCA dataset graph
- [x] Different phones accuraccy graph
- [ ] Different features and which give best results

**Comment by tanjot** [comment]
Write about these points in result section. Order for result section is given in issue #17

**Comment by shubhamchaudhary** [comment]
UCA dataset graph is diff_classifiers. Done.
Phone acc also done.

**Comment by shubhamchaudhary** [comment]
I added some info about diff_phones in 9fd4e76

**Comment by shubhamchaudhary** [comment]
diff_features already has some info in results section itself. Checkout results/diff_features.tex

**Comment by tanjot** [comment]
Need to explain why different phones give  such varying accuracies.

**Comment by tanjot** [comment]
@shubham Is the description about dataset UCA graph done

**Comment by tanjot** [comment]
Different features point to be referred in issue #14
