### ISSUE TITLE
Results section order

### ISSUE THREAD

**Issue by tanjot** [carts-uiet/bus_boarding_paper#17]
1. Dataset collected
1. Features classes
1. Classifiers
1. Final features used with SVM
1. Accuracy on different phones

**Comment by shubhamchaudhary** [comment]
I have divided results section into multiple files. Now we need to juggle stuff around and make any new file needed as per story description.

**Comment by shubhamchaudhary** [comment]
I think the order can be 2, 3, 5, 4.
We don't have anything about 1 in results yet.

**Comment by tanjot** [comment]
Yes, we can just mention a line or two about 1.

**Comment by tanjot** [comment]
Chang order to 3, 2, 4, 5

**Comment by tanjot** [comment]
Added information about dataset collection # 7b7300dfb3ec10e93049a4549a6aacbdf7d4a698
