### ISSUE TITLE
figure 2 size

### ISSUE THREAD

**Issue by shubhamchaudhary** [carts-uiet/bus_boarding_paper#3]
Change the size of figure 2 to fit in a 'human visible' way. Maybe use some other plotter or use some other plotting style(bar graph, line graph etc.)

**Comment by shubhamchaudhary** [comment]
We can show expert and predicted idx in a graph.
(Maybe add acceleration in background of this graph - NOT NEEDED RIGHT NOW)

**Comment by tanjot** [comment]
Easiest using octave, just execute runner(summer 2014/v3) in octave with the csv file.

**Comment by tanjot** [comment]
Plotted graphs, need to select out of those

**Comment by shubhamchaudhary** [comment]
Share dropbox folder

**Comment by shubhamchaudhary** [comment]
> Easiest using octave, just execute runner(summer 2014/v3) in octave with the csv file

Try plot.ly
