### ISSUE TITLE
Remove inconsistent columns in results section

### ISSUE THREAD

**Issue by shubhamchaudhary** [carts-uiet/bus_boarding_paper#4]
Some data in results section is inconsistent. This issue needs that data updated.

##### Acceptance Criterion
- [ ] Result section contains consistent data that shows accuracy increase with frequency domain features

**Comment by shubhamchaudhary** [comment]
Added acceptance criterion

**Comment by tanjot** [comment]
Collected data, need changes in paper

**Comment by tanjot** [comment]
Removed two tables tables for features. Follow issue #14
