### ISSUE TITLE
diff feature and which give best result

### ISSUE THREAD

**Issue by shubhamchaudhary** [carts-uiet/bus_boarding_paper#8]
Feature to try:
- [ ] Mean, Std
- [ ] Mean, Std, DC Component, Energy
- [ ] DC Component, Energy

##### Acceptance Criterion
- [ ] A table that shows different features and comparison

**Comment by shubhamchaudhary** [comment]
What need to be done in this?

**Comment by shubhamchaudhary** [comment]
AFAICT this story demands that we create a table comparing different features.

**Comment by shubhamchaudhary** [comment]
I have updated acceptance criterion and a list of todo given above assumption.

**Comment by tanjot** [comment]
Follow issue #14
